### ISSUE TITLE
"Format()" token syntax highlighting broken when inside square brackets

### ISSUE THREAD

**Issue by swirle13** [pjmiravalle/vscode-terraform-advanced-syntax-highlighting#12]
Small example, with editor tokens and scopes provided.

`format(...)` is highlighted correctly when by itself
![image](https://github.com/user-attachments/assets/e89597ce-fc76-4ed3-8bf3-a5318ece7371)

but when within square brackets, it converts to thinking it is highlighting `for`
![image](https://github.com/user-attachments/assets/523c2ee3-a2f1-40d6-8bf6-60b586884991)

this behavior does not exist when `format` is within parentheses or curly braces, only square brackets.

**Comment by swirle13** [comment]
I believe the behavior stems from the pattern for "for" lacking the word boundary regexes https://github.com/pjmiravalle/vscode-terraform-advanced-syntax-highlighting/blob/main/syntaxes/terraform.json#L558-L569

After trying and building locally, I can confirm it fixes the issue. 
![image](https://github.com/user-attachments/assets/3d58e077-ab82-4d02-9ff1-ff4154c527ef)

I'll open a pull request for this, should be a quick, single line fix.

**Comment by swirle13** [comment]
@pjmiravalle Figured I'd tag you since your issues don't auto-assign yourself

**Comment by pjmiravalle** [comment]
Resolved in #13, and released in [`v1.4.3`](https://github.com/pjmiravalle/vscode-terraform-advanced-syntax-highlighting/releases/tag/v1.4.3).
