### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\Users\username\.vscode\extensions\pjmiravalle.terraform-advanced-syntax-highlighting-1.3.0\language-configuration.json'

### ISSUE THREAD

**Issue by jwmosley** [pjmiravalle/vscode-terraform-advanced-syntax-highlighting#4]
The extension doesn't seem to be running.  I see this error in the Output tab:

```
[01:50:39.774] Unhandled rejection: Error: ENOENT: no such file or directory, open 'c:\Users\username\.vscode\extensions\pjmiravalle.terraform-advanced-syntax-highlighting-1.3.0\language-configuration.json'
```

I notice that the folder doesn't have a "language-configuration.json" file, but it does have a "language-configuration**s**.json" file.  Did something go wrong with the installation?

Thanks for your help.

**Comment by pjmiravalle** [comment]
Hi @jwmosley, thanks for posting this issue! I just went ahead and fixed this in the latest release here: [v1.3.1](https://github.com/pjmiravalle/vscode-terraform-advanced-syntax-highlighting/releases/tag/v1.3.1).
