### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by addison-martin1** [pjmiravalle/vscode-terraform-advanced-syntax-highlighting#8]
In the before/after sections, is it possible to show this in plain text, or update the image
<img width="1551" alt="Screen Shot 2021-09-24 at 12 00 03 PM" src="https://user-images.githubusercontent.com/79336963/134727712-baf22f14-8a89-47ba-ab1b-d55395916195.png">
s?

**Comment by pjmiravalle** [comment]
Fixed in the [latest release](https://github.com/pjmiravalle/vscode-terraform-advanced-syntax-highlighting/releases/tag/v1.4.1).
