### ISSUE TITLE
Comment Toggle Syntax with Hotkey

### ISSUE THREAD

**Issue by wazoo** [pjmiravalle/vscode-terraform-advanced-syntax-highlighting#9]
I just recently figured out that this plugin is the culprit for why I started getting /* */ for terraform comments when using the cmd+/ in vscode.  According to the [HCL Syntax documentation](https://www.terraform.io/language/syntax/configuration#comments) # comments should be used in most cases.

I wasn't sure if I should make this a feature request or not, it seems like a bug to me but my request is either to make this a configurable option or stop using /* */ comments all together in favor of #.  

I have experienced this over many versions of vscode, macOS, all plugins but I can provide that information if it is relevant however disabling this plugin fixes this issue every time now that I know what causes it.  Also of note, the official HashiCorp extension is the other one I am using and it seems to function as expected.

**Comment by Wolfium** [comment]
> I just recently figured out that this plugin is the culprit for why I started getting /* */ for terraform comments when using the cmd+/ in vscode. According to the [HCL Syntax documentation](https://www.terraform.io/language/syntax/configuration#comments) # comments should be used in most cases.
> 
> I wasn't sure if I should make this a feature request or not, it seems like a bug to me but my request is either to make this a configurable option or stop using /* */ comments all together in favor of #.
> 
> I have experienced this over many versions of vscode, macOS, all plugins but I can provide that information if it is relevant however disabling this plugin fixes this issue every time now that I know what causes it. Also of note, the official HashiCorp extension is the other one I am using and it seems to function as expected.

Same here, figured out the same being this extension the origin of the weird behavior

While syntax highlight is really good and really like it, 
But is making working weird about commenting lines, almost unusable

Details below....
Instead of line comment with hash at the beginning of each line it does block comments with 
/* commented block */ 
Which breaks commenting and syntax highlight when there is another block comment inside

**Comment by pjmiravalle** [comment]
Hi all,

Sorry for the delay in responding to this, but I'm more than happy to work through a fix. I'll keep y'all posted as I find a solution.

Thanks for your feedback!

**Comment by inflatador** [comment]
Just wanted to add that I'm affected as well, thanks everyone for reporting.

**Comment by pjmiravalle** [comment]
Fixed in the [latest release](https://github.com/pjmiravalle/vscode-terraform-advanced-syntax-highlighting/releases/tag/v1.4.1)!

Thank you all for raising this concern, and @TrongTheAlpaca for highlighting a fix.
